# This file stores configurations for your Shopify app.

scopes = "read_products,write_products,read_product_listings,read_shipping,write_shipping,read_orders,read_all_orders,read_customer_payment_methods,read_purchase_options,write_purchase_options,read_payment_mandate,write_payment_mandate"
