# This file stores configurations for your Shopify app.

scopes = "read_products,write_products,read_product_listings,read_shipping,write_shipping,read_orders,read_purchase_options,write_purchase_options,read_checkouts,write_checkouts"
